#ifndef MEW_UI_API_H
#define MEW_UI_API_H

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <wchar.h>
#include "mewjector.h"

#ifdef __cplusplus
extern "C"
{
#endif

#define MEW_UI_API_VERSION 1U
#define MEW_MAX_BUTTON_RECORDS 256U
#define MEW_BUTTON_ROLE_MAX 128U
#define MEW_TEXT_BUFFER_MAX 512U
#define MEW_BUTTON_LABEL_TARGET_MAX 16U
#define MEW_BUTTON_STATE_NODE_NAME_COUNT 6U

#define MEW_RVA_MEWDIRECTOR_SINGLETON 0x013C7BD0ULL // This points at the process-wide MewDirector singleton used to walk loaded scenes...
#define MEW_RVA_ALLOC_COMPONENT_FROM_TYPE 0x009590C0ULL // This is the engine allocator that creates components from a type descriptor...
#define MEW_RVA_SCENE_REGISTER_COMPONENT 0x0095AF40ULL // This registers a component with the scene manager so the game knows about it...
#define MEW_RVA_RESIZE_PTR_ARRAY 0x00D3CF88ULL // This grows the engine pointer arrays used by scene buckets...
#define MEW_RVA_CONTEXT_FROM_MANAGER 0x0095AFE0ULL // This asks the scene manager for a UI context, creating or attaching one when safe...
#define MEW_RVA_SCENE_READY_UPDATE 0x0095A850ULL // This is the scene-ready update pass where mod UI work can run safely...
#define MEW_RVA_SCENE_READY_UPDATE_STOLEN_BYTES 15 // This is the trampoline byte count for the scene-ready update hook...
#define MEW_RVA_CONTEXT_ATTACH_COMPONENT_REF 0x00047B60ULL // This appends a component reference into the UI context list...
#define MEW_RVA_UI_FIND_CHILD_BY_NAME 0x000E7370ULL // This finds a direct UI child by its engine narrow-string name...
#define MEW_RVA_FIND_UI_CHILD_ALT 0x00059B70ULL // This is the root-owned child lookup used by the text owner helpers...
#define MEW_RVA_UI_FIND_NODE_BY_PATH_OR_NAME 0x00988970ULL // This finds a UI node recursively by path or plain name...
#define MEW_RVA_UI_ROOT_SET_TEXT_STRING 0x0096C280ULL // This sets root-owned text from a localization key by node name...
#define MEW_RVA_UI_ROOT_SET_TEXT_WIDE_STRING 0x0096C2F0ULL // This sets root-owned text from an already-built wide string...
#define MEW_RVA_INIT_NARROW_STRING 0x00052640ULL // This builds the engine narrow string wrapper used before lookup calls...
#define MEW_RVA_DESTROY_NARROW_STRING 0x000522D0ULL // This destroys heap-backed engine narrow strings after the game is done with them...
#define MEW_RVA_ASSIGN_NARROW_STRING_LITERAL 0x00051C20ULL // This writes plain role-name text into an engine narrow string slot...
#define MEW_RVA_MOVE_WIDE_STRING 0x000623C0ULL // This moves an engine wide string into another engine-owned wide string...
#define MEW_RVA_ASSIGN_WIDE_STRING_DATA 0x0005ABC0ULL // This copies raw wchar text into an engine wide string slot...
#define MEW_RVA_COPY_WIDE_STRING_OBJECT 0x0005AAD0ULL // This copy-constructs a temporary wide string for text setter calls...
#define MEW_RVA_DESTROY_WIDE_STRING 0x00051DE0ULL // This destroys engine wide strings that may own heap memory...
#define MEW_RVA_LOCALIZE_NARROW_KEY 0x00956270ULL // This turns a localization key into the wide text the UI actually displays...
#define MEW_RVA_SET_TEXT_ELEMENT_STRING 0x0097E390ULL // This sets a text element from either a key or direct narrow text...
#define MEW_RVA_SET_TEXT_ELEMENT_WIDE_STRING 0x0097E4A0ULL // This sets a text element from an already-built wide string...
#define MEW_RVA_BUTTON_CONSTRUCT 0x001411A0ULL // This runs the real Button constructor after allocation...
#define MEW_RVA_BUTTON_SETUP_FROM_NODE 0x0096DDF0ULL // This copies setup data from a UI node into a Button component...
#define MEW_RVA_BUTTON_UPDATE 0x0096DF30ULL // This is Button update, where state changes and label swaps happen...
#define MEW_RVA_BUTTON_ACTIVATE 0x0096E4E0ULL // This is Button activate, used to detect accepted click edges...
#define MEW_RVA_BUTTON_ACTIVATE_STOLEN_BYTES 15 // This is the trampoline byte count for the activate hook...
#define MEW_RVA_BUTTON_CAN_ACTIVATE 0x0096E6F0ULL // This is the game interactability check before a button can activate...
#define MEW_RVA_BUTTON_CAN_ACTIVATE_STOLEN_BYTES 15 // This is the trampoline byte count for the can-activate hook...
#define MEW_RVA_BUTTON_TYPE_DESCRIPTOR 0x013E54F0ULL // This points at the global Button type descriptor used for allocation...
#define MEW_RVA_LOCALIZATION_MANAGER 0x013B2590ULL // This points at the global localization manager used for label and text keys...

#define MEW_OFF_MEWDIRECTOR_DIRECTOR 0x28U // This reaches the root scene collection from the MewDirector singleton...
#define MEW_OFF_SCENE_COMPONENT_LISTS 0x18U // This reaches the scene manager component-list table...
#define MEW_OFF_SCENE_DOING_DESTRUCTION 0x4B0U // This checks whether the scene is tearing down before touching UI state...
#define MEW_OFF_SCENE_NAME 0x4B8U // This reaches the scene manager narrow-string name used for scene matching...
#define MEW_OFF_SCENE_SKIP_READY_TICK_A 0x4D8U // This gate tells us the scene-ready UI tick should wait...
#define MEW_OFF_SCENE_SKIP_READY_TICK_B 0x4DAU // This second gate also tells us the scene-ready UI tick should wait...
#define MEW_OFF_SCENE_SKIP_READY_TICK_C 0x4DBU // This third gate also tells us the scene-ready UI tick should wait...
#define MEW_OFF_COMPONENT_FLAGS_A 0x0CU // This reaches the base component flag byte for setup and click membership...
#define MEW_OFF_COMPONENT_FLAGS_B 0x0DU // This reaches the base component flag byte for render membership...
#define MEW_OFF_COMPONENT_LAYER 0x0EU // This reaches the component layer copied from the owning UI context...
#define MEW_OFF_COMPONENT_ENABLED 0x10U // This reaches the enabled byte that gates normal component updates...
#define MEW_OFF_COMPONENT_CONTEXT 0x18U // This reaches the component back-pointer to its UI context...
#define MEW_OFF_COMPONENT_MANAGER 0x20U // This reaches the component back-pointer to its scene manager...
#define MEW_OFF_COMPONENT_MANAGER_HEADER 0x28U // This reaches the manager header pointer mirrored from the scene manager...
#define MEW_OFF_BUTTON_NODE 0x48U // This reaches the source UI node stored on a Button...
#define MEW_OFF_BUTTON_MOUSE_GROUP 0x50U // This reaches the mouse/input grouping data used near can-activate...
#define MEW_OFF_BUTTON_ROLE_NAME 0x1F8U // This reaches the role-name string used to find and reuse buttons...
#define MEW_OFF_BUTTON_LABEL_TEXT 0x1B8U // This reaches the visible Button label wide string...
#define MEW_OFF_BUTTON_LOCK_DISABLE_BYTE 0x58U // This reaches the lock byte Button update checks before forcing selected state...
#define MEW_OFF_BUTTON_ACTIVATE_BYTE 0x59U // This reaches the activate gate checked at the start of Button activate...
#define MEW_OFF_BUTTON_MOUSE_STRICT_BYTE 0x5BU // This reaches the strict-mouse byte checked by can-activate...
#define MEW_OFF_BUTTON_STATE 0x2F0U // This reaches the current Button state enum...
#define MEW_OFF_BUTTON_PREVIOUS_STATE 0x2F8U // This reaches the previous Button state slot...
#define MEW_OFF_BUTTON_MODE 0x2FCU // This reaches the Button mode enum checked before activation fires...
#define MEW_OFF_BUTTON_STATE_NODE_NAMES 0x300U // This reaches the six state-node names Button update can swap between...
#define MEW_OFF_CONTEXT_COMPONENT_REFS 0x20U // This reaches the context-owned vector of component references...
#define MEW_OFF_CONTEXT_LAYER 0x19U // This reaches the context layer copied into new components...
#define MEW_OFF_MANAGER_BUCKET_UPDATE_CAPACITY 0xD8U // This reaches the update bucket capacity field...
#define MEW_OFF_MANAGER_BUCKET_UPDATE_SIZE 0xDCU // This reaches the update bucket size field...
#define MEW_OFF_MANAGER_BUCKET_UPDATE_DATA 0xE0U // This reaches the update bucket pointer array...
#define MEW_OFF_MANAGER_BUCKET_CLICK_CAPACITY 0x120U // This reaches the click/input bucket capacity field...
#define MEW_OFF_MANAGER_BUCKET_CLICK_SIZE 0x124U // This reaches the click/input bucket size field...
#define MEW_OFF_MANAGER_BUCKET_CLICK_DATA 0x128U // This reaches the click/input bucket pointer array...
#define MEW_OFF_MANAGER_BUCKET_RENDER_CAPACITY 0x360U // This reaches the render bucket capacity field...
#define MEW_OFF_MANAGER_BUCKET_RENDER_SIZE 0x364U // This reaches the render bucket size field...
#define MEW_OFF_MANAGER_BUCKET_RENDER_DATA 0x368U // This reaches the render bucket pointer array...
#define MEW_SIZE_BUTTON 0x3C0U // Concrete button object size cleared before construction...
#define MEW_SIZE_CALLBACK_BINDING_SCRATCH 0x40U // Temporary callback-binding scratch block passed into setup-from-node...

#define MEW_COMPONENT_FLAGS_A_KEEP_SETUP_MASK 0xFCU // Keeps the non-setup bits while preparing setup membership...
#define MEW_COMPONENT_FLAGS_A_SET_SETUP_MASK 0x04U // Sets the setup/register bit expected before scene registration...
#define MEW_COMPONENT_FLAGS_A_CLICKABLE_MASK 0x08U // Marks the component as click/input bucket eligible...
#define MEW_COMPONENT_FLAGS_A_POST_CLICK_MASK 0x0FU // Leaves the post-click flags in the state expected by the engine...
#define MEW_COMPONENT_FLAGS_B_KEEP_RENDER_MASK 0xF8U // Keeps the non-render bits while preparing render membership...
#define MEW_COMPONENT_FLAGS_B_SET_RENDER_MASK 0x08U // Sets the render bucket bit before insertion...
#define MEW_COMPONENT_FLAGS_B_POST_RENDER_MASK 0x8FU // Leaves render flags in the state expected after insertion...

typedef enum MewButtonState
{
    MEW_BUTTON_STATE_IDLE = 0,
    MEW_BUTTON_STATE_HOVERED = 1,
    MEW_BUTTON_STATE_PRESSED = 2,
    MEW_BUTTON_STATE_SELECTED = 3,
    MEW_BUTTON_STATE_DISABLED = 4,
    MEW_BUTTON_STATE_TRANSITION = 5,
    MEW_BUTTON_STATE_INVALID = -1
} MewButtonState;

typedef enum MewButtonEvent
{
    MEW_BUTTON_EVENT_STATE_CHANGED = 0,
    MEW_BUTTON_EVENT_HOVER_ENTER = 1,
    MEW_BUTTON_EVENT_HOVER_EXIT = 2,
    MEW_BUTTON_EVENT_PRESS_BEGIN = 3,
    MEW_BUTTON_EVENT_PRESS_CANCEL = 4,
    MEW_BUTTON_EVENT_CLICK = 5,
    MEW_BUTTON_EVENT_DISABLED = 6
} MewButtonEvent;

typedef enum MewButtonInteractOverride
{
    MEW_BUTTON_INTERACT_GAME_DEFAULT = 0,
    MEW_BUTTON_INTERACT_FORCE_DISABLED = 1,
    MEW_BUTTON_INTERACT_FORCE_ENABLED = 2,
    MEW_BUTTON_INTERACT_CALLBACK = 3
} MewButtonInteractOverride;

// Mirrors the game narrow string layout, <= 15 bytes live inline, larger strings use heap_ptr...
typedef struct MewNarrowString
{
    union
    {
        char* heap_ptr;
        char inline_buf[16];
    } storage;
    uint64_t size;
    uint64_t capacity;
} MewNarrowString;

// Mirrors the game wide string layout, <= 7 wchar_t values live inline, larger strings use heap_ptr...
typedef struct MewWideString
{
    union
    {
        wchar_t* heap_ptr;
        wchar_t inline_buf[8];
    } storage;
    uint64_t size;
    uint64_t capacity;
} MewWideString;

#define MEW_TEXT_FORMAT_MAX_SEGMENTS 64U
#define MEW_TEXT_FORMAT_MAX_VALUES 16U
#define MEW_TEXT_FORMAT_VALUE_BUFFER_MAX 96U

// Supported typed values for prepared localized text formatting...
typedef enum MewUITextFormatValueType
{
    MEW_UI_TEXT_FORMAT_VALUE_STRING = 0,
    MEW_UI_TEXT_FORMAT_VALUE_INT32 = 1,
    MEW_UI_TEXT_FORMAT_VALUE_UINT32 = 2,
    MEW_UI_TEXT_FORMAT_VALUE_FLOAT = 3,
    MEW_UI_TEXT_FORMAT_VALUE_DOUBLE = 4
} MewUITextFormatValueType;

typedef struct MewUITextFormatValue
{
    MewUITextFormatValueType type;
    uint32_t precision;
    union
    {
        const char* string_value;
        int32_t int32_value;
        uint32_t uint32_value;
        float float_value;
        double double_value;
    } data;
} MewUITextFormatValue;

typedef struct MewUITextFormatSegment
{
    MewWideString literal;
    uint32_t value_index;
    uint8_t is_value;
} MewUITextFormatSegment;

// Cached localized text binding for fast per-frame updates of {v0}, {v1}, etc. placeholders...
typedef struct MewUITextFormat
{
    void* scene_manager;
    void* text_element;
    MewUITextFormatSegment segments[MEW_TEXT_FORMAT_MAX_SEGMENTS];
    uint32_t segment_count;
    uint32_t value_count;
    uint8_t prepared;
} MewUITextFormat;

// Back-compat alias for the original one-value prepared text binding API...
typedef MewUITextFormat MewUITextFormatValue0;

// Engine pointer-vector triplet used by manager buckets and context refs...
typedef struct MewPodVectorPtr
{
    uint32_t capacity;
    uint32_t size;
    void** data;
} MewPodVectorPtr;

typedef struct MewVectorScenePtr
{
    void** begin;
    void** end;
    void** capacity_end;
} MewVectorScenePtr;

typedef struct MewDirectorRoot
{
    MewVectorScenePtr scenes;
} MewDirectorRoot;

typedef struct MewDirector
{
    uint8_t padding_0[40];
    MewDirectorRoot* director;
} MewDirector;

typedef struct MewComponentVTable
{
    MewNarrowString* (__cdecl* GetObjectTypeSTR)(const void* self, MewNarrowString* result);
    int32_t (__cdecl* GetObjectType)(const void* self);
    uint8_t (__cdecl* TypeInHierarchy)(const void* self, MewNarrowString* type);
} MewComponentVTable;

// Minimal base component header, offsets above are verified against constructor/update code...
typedef struct MewComponent
{
    const MewComponentVTable* vtable;
    uint32_t object_id;
    uint8_t flags_a;
    uint8_t flags_b;
    uint8_t layer;
    uint8_t deleted;
    uint8_t enabled;
    uint8_t started;
    uint8_t padding_12[6];
    void* context;
    void* manager;
    void* manager_header;
} MewComponent;

typedef void (__cdecl* MewButtonCallback)(void* button, MewButtonEvent event_type, MewButtonState old_state, MewButtonState new_state, void* user_data);
typedef uint8_t (__cdecl* MewButtonCanInteractCallback)(void* button, uint8_t original_result, void* user_data);

typedef void (__cdecl* MewUITickCallback)(void* user_data);

typedef enum MewUISceneRefreshResult
{
    MEW_UI_SCENE_REFRESH_UNAVAILABLE = 0,
    MEW_UI_SCENE_REFRESH_UNCHANGED = 1,
    MEW_UI_SCENE_REFRESH_LOADED = 2,
    MEW_UI_SCENE_REFRESH_CHANGED = 3,
    MEW_UI_SCENE_REFRESH_UNLOADED = 4
} MewUISceneRefreshResult;

typedef struct MewUISceneBinding MewUISceneBinding;
typedef void (__cdecl* MewUISceneRefreshCallback)(MewUISceneBinding* binding, MewUISceneRefreshResult result, void* old_scene_manager, void* new_scene_manager, void* user_data);

struct MewUISceneBinding
{
    char scene_name[MEW_TEXT_BUFFER_MAX];
    void* scene_manager;
    uint32_t generation;
    uint8_t active;
    MewUISceneRefreshCallback callback;
    void* user_data;
};

// Creation payload for turning an existing UI node into a live button component...
typedef struct MewButtonCreateInfo
{
    void* scene_manager;
    void* context;
    void* root_node;
    void* button_node;
    const char* node_name;
    const char* role_name;
    const char* label_key;
    const char* label_text;
    uint8_t enabled;
    uint8_t activate_enabled;
    uint8_t strict_mouse;
    MewButtonInteractOverride interact_override;
    MewButtonCanInteractCallback can_interact_callback;
    void* can_interact_user_data;
    MewButtonCallback callback;
    void* user_data;
} MewButtonCreateInfo;

typedef struct MewNamedButtonCreateInfo
{
    const char* scene_name;
    const char* node_name;
    const char* role_name;
    const char* label_key;
    const char* label_text;
    uint8_t enabled;
    uint8_t activate_enabled;
    uint8_t strict_mouse;
    MewButtonInteractOverride interact_override;
    MewButtonCanInteractCallback can_interact_callback;
    void* can_interact_user_data;
    MewButtonCallback callback;
    void* user_data;
} MewNamedButtonCreateInfo;

// Local tracking record for callbacks, reuse, and interaction overrides...
typedef struct MewButtonRecord
{
    uint8_t used;
    uint8_t owned_by_ui;
    uint8_t click_from_hook_seen;
    uint8_t suppress_original_activate;
    char role_name[MEW_BUTTON_ROLE_MAX];
    void* scene_manager;
    void* context;
    void* root_node;
    void* button_node;
    void* button;
    MewButtonState last_state;
    MewButtonCallback callback;
    void* user_data;
    MewButtonInteractOverride interact_override;
    MewButtonCanInteractCallback can_interact_callback;
    void* can_interact_user_data;
} MewButtonRecord;

typedef void* (__fastcall* MewFnFindChildByName)(void* root_node, MewNarrowString* name);
typedef void* (__fastcall* MewFnFindNodeByPathOrName)(void* root_node, MewNarrowString* name, uint8_t preserve_path_mode);
typedef void (__fastcall* MewFnUIRootSetTextString)(void* ui_root_owner, MewNarrowString* node_name, MewNarrowString* text_key);
typedef void (__fastcall* MewFnUIRootSetTextWideString)(void* ui_root_owner, MewNarrowString* node_name, MewWideString* text);
typedef void* (__fastcall* MewFnContextFromManager)(void* scene_manager);
typedef void* (__fastcall* MewFnAllocComponentFromType)(void* type_descriptor);
typedef void* (__fastcall* MewFnButtonConstruct)(void* button);
typedef void (__fastcall* MewFnSceneRegisterComponent)(void* scene_manager, void* component);
typedef void* (__fastcall* MewFnResizePtrArray)(void* old_data, uint64_t new_size_bytes);
typedef void (__fastcall* MewFnContextAttachComponentRef)(void* context_component_refs, void** component_ref);
typedef void (__fastcall* MewFnButtonSetupFromNode)(void* button, void* node, void* callback_binding, MewNarrowString* label_key);
typedef MewNarrowString* (__fastcall* MewFnInitNarrowString)(MewNarrowString* out_string, const char* text);
typedef void (__fastcall* MewFnDestroyNarrowString)(MewNarrowString* value);
typedef void* (__fastcall* MewFnAssignNarrowStringLiteral)(void* target_string, const char* text, uint64_t length);
typedef void* (__fastcall* MewFnMoveWideString)(void* target_string, MewWideString* source_string);
typedef void* (__fastcall* MewFnAssignWideStringData)(void* target_string, const wchar_t* source_data, uint64_t source_length);
typedef MewWideString* (__fastcall* MewFnCopyWideStringObject)(MewWideString* target_string, const MewWideString* source_string);
typedef void (__fastcall* MewFnDestroyWideString)(MewWideString* value);
typedef MewWideString* (__fastcall* MewFnLocalizeNarrowKey)(void* localization_manager, MewWideString* output_string, MewNarrowString* key_string);
typedef void* (__fastcall* MewFnSetTextElementString)(void* text_element, MewNarrowString* text, uint8_t use_localization_key, uint8_t commit_immediately);
typedef void* (__fastcall* MewFnSetTextElementWideString)(void* text_element, MewWideString* text, uint8_t force_update_existing_text, uint8_t commit_immediately);
typedef void (__fastcall* MewFnButtonActivate)(void* button, uint8_t from_mouse);
typedef uint8_t (__fastcall* MewFnButtonCanActivate)(void* button, int32_t button_index, uint8_t strict_mouse);
typedef void (__fastcall* MewFnSceneReadyUpdate)(void* scene_manager);

// Starts the UI API and defers hook install until Mewjector and the game are ready...
int MewUI_Start(const char* owner_name, int hook_priority, uint32_t bootstrap_interval_ms, uint32_t ui_interval_ms, MewUITickCallback tick_callback, void* user_data);
// Stops the timer path, clears hooks owned by the API, and resets tracked state...
void MewUI_Stop(void);
// Returns nonzero once the API has installed its hooks and can run UI work...
int MewUI_IsReady(void);
// Returns the resolved Mewjector API pointer when it is available...
const MewjectorAPI* MewUI_GetMewjector(void);
// Writes a log message through Mewjector using the current owner name...
void MewUI_LogMessage(const char* format, ...);
// Turns the API debug chatter on or off...
void MewUI_SetDebugLogsEnabled(bool enabled);
// Checks whether the API debug chatter is currently enabled...
bool MewUI_GetDebugLogsEnabled(void);

// Installs the scene-ready and button hooks using an already-resolved Mewjector API...
int MewUI_Init(const MewjectorAPI* api, const char* owner_name, int hook_priority);
// Clears API-owned records and cached hook pointers without touching mod state...
void MewUI_Shutdown(void);
// Polls tracked buttons so state callbacks stay in sync between click events...
void MewUI_Tick(void);
// Checks whether a scene manager is safe enough for UI work this frame...
int MewUI_IsSceneReadyForUITick(void* scene_manager);
// Returns the global MewDirector singleton when the game base is known...
MewDirector* MewUI_GetMewDirector(void);
// Finds a loaded scene by matching the engine scene name string...
void* MewUI_GetSceneByName(const char* scene_name);
// Gets or creates the scene UI context, so avoid using it as a harmless probe...
void* MewUI_GetContextFromScene(void* scene_manager);
// Initializes a scene binding that can track load, unload, and scene-pointer changes...
void MewUI_InitSceneBinding(MewUISceneBinding* binding, const char* scene_name, MewUISceneRefreshCallback callback, void* user_data);
// Clears a scene binding back to an empty safe state...
void MewUI_ClearSceneBinding(MewUISceneBinding* binding);
// Refreshes a scene binding and reports whether the target scene changed...
MewUISceneRefreshResult MewUI_RefreshSceneBinding(MewUISceneBinding* binding);
// Returns the live scene pointer from a binding when it is still safe to use...
void* MewUI_GetSceneBindingScene(const MewUISceneBinding* binding);
// Returns the binding generation so a mod can notice scene reloads...
uint32_t MewUI_GetSceneBindingGeneration(const MewUISceneBinding* binding);
// Returns nonzero when the binding currently has a usable scene...
int MewUI_IsSceneBindingActive(const MewUISceneBinding* binding);
// Returns a friendly scene-refresh result name for logs...
const char* MewUI_GetSceneRefreshResultName(MewUISceneRefreshResult result);
// Finds a direct child under a UI node using the game lookup helper...
void* MewUI_FindChildByName(void* root_node, const char* child_name);
// Finds a UI node anywhere in a scene by its node name...
void* MewUI_FindNodeInSceneByName(void* scene_manager, const char* node_name);
// Finds a root-owned child in a scene by name...
void* MewUI_FindChildByNameInScene(void* scene_manager, const char* child_name);
// Sets one text element from a localization key...
int MewUI_SetTextElementFromLocalizationKey(void* text_element, const char* key);
// Sets one text element from a localization key with one placeholder value...
int MewUI_SetTextElementFromLocalizationKeyValue(void* text_element, const char* key, const char* value0);
// Sets one text element from a localization key with multiple placeholder values...
int MewUI_SetTextElementFromLocalizationKeyValues(void* text_element, const char* key, const char* const* values, uint32_t value_count);
// Finds a child text node under a root node and sets it from a key...
int MewUI_SetTextChildFromLocalizationKey(void* root_node, const char* child_name, const char* key);
// Finds a child text node and fills one localized placeholder...
int MewUI_SetTextChildFromLocalizationKeyValue(void* root_node, const char* child_name, const char* key, const char* value0);
// Finds a child text node and fills multiple localized placeholders...
int MewUI_SetTextChildFromLocalizationKeyValues(void* root_node, const char* child_name, const char* key, const char* const* values, uint32_t value_count);
// Finds a scene text node and sets it from a localization key...
int MewUI_SetTextFromLocalizationKey(const char* scene_name, const char* child_name, const char* key);
// Finds a scene text node and fills one localized placeholder...
int MewUI_SetTextFromLocalizationKeyValue(const char* scene_name, const char* child_name, const char* key, const char* value0);
// Finds a scene text node and fills multiple localized placeholders...
int MewUI_SetTextFromLocalizationKeyValues(const char* scene_name, const char* child_name, const char* key, const char* const* values, uint32_t value_count);
// Prepares a cached localized text format so repeated updates are cheap...
int MewUI_PrepareTextFormat(const char* scene_name, const char* child_name, const char* key, MewUITextFormat* io_format);
// Applies string values to a prepared text format...
int MewUI_SetPreparedTextFormatValues(MewUITextFormat* format, const char* const* values, uint32_t value_count);
// Applies typed values to a prepared text format...
int MewUI_SetPreparedTextFormatTypedValues(MewUITextFormat* format, const MewUITextFormatValue* values, uint32_t value_count);
// Applies one string value to a prepared text format...
int MewUI_SetPreparedTextFormatValue(MewUITextFormat* format, const char* value0);
// Applies one signed integer value to a prepared text format...
int MewUI_SetPreparedTextFormatInt32(MewUITextFormat* format, int32_t value0);
// Applies one unsigned integer value to a prepared text format...
int MewUI_SetPreparedTextFormatUInt32(MewUITextFormat* format, uint32_t value0);
// Applies one float value to a prepared text format with precision...
int MewUI_SetPreparedTextFormatFloat(MewUITextFormat* format, float value0, uint32_t precision);
// Applies one double value to a prepared text format with precision...
int MewUI_SetPreparedTextFormatDouble(MewUITextFormat* format, double value0, uint32_t precision);
// Releases cached prepared text segments and clears the format...
void MewUI_ClearTextFormat(MewUITextFormat* format);
// Prepares the one-value text format helper...
int MewUI_PrepareTextFormatValue0(const char* scene_name, const char* child_name, const char* key, MewUITextFormatValue0* io_format);
// Sets the one-value text format with an unsigned integer...
int MewUI_SetPreparedTextFormatValue0UInt32(MewUITextFormatValue0* format, uint32_t value);
// Clears the one-value text format helper...
void MewUI_ClearTextFormatValue0(MewUITextFormatValue0* format);
// Creates a UI node into a new Button component using full create info...
void* MewUI_CreateButtonFromNode(const MewButtonCreateInfo* create_info);
// Creates a named node into a Button when the scene and context are already known...
void* MewUI_CreateButtonFromNamedNode(const MewButtonCreateInfo* create_info);
// Creates a Button in a scene using a node already listed in the create info...
void* MewUI_CreateButtonInScene(const MewButtonCreateInfo* create_info);
// Creates or reuses a scene button from simple named-button settings...
void* MewUI_SetupButtonInScene(const MewNamedButtonCreateInfo* create_info, void** io_button, int* out_created);
// Creates or reuses a button and applies its label from a localization key...
void* MewUI_SetupButtonFromLocalizationKey(const char* scene_name, const char* node_name, const char* role_name, const char* label_key, MewButtonCallback callback, void* user_data, void** io_button, int* out_created);
// Creates or reuses a button while leaving its label alone...
void* MewUI_SetupButtonWithoutLabel(const char* scene_name, const char* node_name, const char* role_name, MewButtonCallback callback, void* user_data, void** io_button, int* out_created);
// Finds one tracked or scene-owned button by role name...
void* MewUI_FindButtonByRole(void* scene_manager, const char* role_name);
// Finds every matching button role up to the output buffer capacity...
uint32_t MewUI_FindButtonsByRole(void* scene_manager, const char* role_name, void** out_buttons, uint32_t out_button_capacity);
// Finds a button by the UI node it was set up from...
void* MewUI_FindButtonByNodeName(void* scene_manager, const char* node_name);
// Hooks a game-created button by node name while keeping the original click path...
void* MewUI_HookExistingButtonByNodeName(const char* scene_name, const char* node_name, MewButtonCallback callback, void* user_data, void** io_button);
// Hooks a game-created button by node name and suppresses the original click path...
void* MewUI_HookExistingButtonByNodeNameExclusive(const char* scene_name, const char* node_name, MewButtonCallback callback, void* user_data, void** io_button);
// Tracks an existing button so a callback can observe it...
int MewUI_RegisterExistingButton(void* button, const char* role_name, MewButtonCallback callback, void* user_data);
// Controls whether a tracked button skips the original activate routine...
int MewUI_SetButtonSuppressOriginalActivate(void* button, int suppress_original_activate);
// Writes a stable role name onto a button for later lookup...
int MewUI_SetButtonRoleName(void* button, const char* role_name);
// Copies a button role name into a buffer...
int MewUI_GetButtonRoleName(void* button, char* out_buffer, size_t out_buffer_size);
// Reads the current button state from the engine field...
MewButtonState MewUI_GetButtonState(void* button);
// Writes the current and previous button state fields...
int MewUI_SetButtonState(void* button, MewButtonState state);
// Sets a button label from a localization key...
int MewUI_SetButtonLabelFromLocalizationKey(void* button, const char* key);
// Sets a button label from a localization key with one value...
int MewUI_SetButtonLabelFromLocalizationKeyValue(void* button, const char* key, const char* value0);
// Sets a button label from a localization key with multiple values...
int MewUI_SetButtonLabelFromLocalizationKeyValues(void* button, const char* key, const char* const* values, uint32_t value_count);
// Sets a button label from direct text...
int MewUI_SetButtonLabelText(void* button, const char* text);
// Clears a button label by setting it to empty text...
int MewUI_ClearButtonLabel(void* button);
// Toggles both the component enabled flag and activation gate...
int MewUI_SetButtonEnabled(void* button, int enabled);
// Forces button interactability on or off without changing game code...
int MewUI_SetButtonInteractable(void* button, int interactable);
// Returns a button to the game default interactability result...
int MewUI_ClearButtonInteractOverride(void* button);
// Lets a callback decide whether a button can interact this frame...
int MewUI_SetButtonCanInteractCallback(void* button, MewButtonCanInteractCallback callback, void* user_data);
// Checks whether the API is currently tracking a button...
int MewUI_IsButtonTracked(void* button);
// Returns the tracking record for a button when one exists...
MewButtonRecord* MewUI_GetButtonRecord(void* button);
// Returns the readable pointer for an engine narrow string...
const char* MewUI_GetNarrowStringData(const MewNarrowString* value);
// Returns the character count for an engine narrow string...
size_t MewUI_GetNarrowStringSize(const MewNarrowString* value);
// Builds a tiny inline wide string for short engine calls...
void MewUI_InitSmallWideString(MewWideString* out_string, const wchar_t* text);
// Returns a friendly button event name for logs...
const char* MewUI_GetButtonEventName(MewButtonEvent event_type);
// Returns a friendly button state name for logs...
const char* MewUI_GetButtonStateName(MewButtonState state);

// Checks whether a scene manager is in its destruction phase...
int MewUI_IsSceneDestroying(void* scene_manager);
// Checks whether a component is currently owned by a scene...
int MewUI_IsComponentInScene(void* scene_manager, void* component);
// Creates or reuses a button from a known UI node...
void* MewUI_SetupButtonFromNode(const MewButtonCreateInfo* create_info, void** io_button, int* out_created);
// Sets scene text from a key when we already have the scene pointer...
int MewUI_SetTextInSceneFromLocalizationKey(void* scene_manager, const char* child_name, const char* key);
// Sets scene text with one value when we already have the scene pointer...
int MewUI_SetTextInSceneFromLocalizationKeyValue(void* scene_manager, const char* child_name, const char* key, const char* value0);
// Sets scene text with multiple values when we already have the scene pointer...
int MewUI_SetTextInSceneFromLocalizationKeyValues(void* scene_manager, const char* child_name, const char* key, const char* const* values, uint32_t value_count);

#ifdef __cplusplus
}
#endif

#endif